### ISSUE TITLE
Disable WordPress Plugin List on Multisite

### ISSUE THREAD

**Issue by MarcWoodyard** [disqus/disqus-wordpress#96]
Under the plugin's settings, there is a section that displays a list of the plugins installed on WordPress. Is there any way to disable this.

I run a multisite network, and I would prefer that my users not have access to this section. 

Thanks,
Marc

**Comment by nmisic** [comment]
Hi, 

I'm having exact same issue.

**Comment by MarcWoodyard** [comment]
Sorry for the late reply, but I just got around to dealing with this issue. Currently, I just removed the `foreach` loop at the bottom of `manage.php` that listed the plugins installed on my network. I would have liked to remove it with a function, but the HTML is hardcoded into the PHP file.
