### ISSUE TITLE
Annoying javascript alert() in pointer.js

### ISSUE THREAD

**Issue by noahwilliamsson** [disqus/disqus-wordpress#97]
Commit 0ea6729ca6544ee4ccd60e5932ef0c6cacde5b64 (ping @ryanvalentin)  introduced a javascript alert() in `disqus/media/js/pointer.js`.  It is present in the latest official release (2.84) of the plugin.

Under certain circumstances the alert() shows up when you load the WordPress customizer page (`/wp-admin/customize.php`).

Would you please consider removing this line from the plugin?

**Comment by Endzakiel** [comment]
I did this comit https://github.com/Endzakiel/disqus-wordpress/commit/fe92f2ddbfb63a9f64a1ed6e564df6b537ce2e2f / pull request https://github.com/disqus/disqus-wordpress/pull/98 to clean it.

**Comment by mattrobenolt** [comment]
This should be fixed with #98
